## numpy array and basics
learn about numpy with chai or code


In [12]:
import numpy as np

cresting array from list

In [15]:
arr_1d = np.array([1, 2, 3, 4,5 ])
print("1D Array:",arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:", arr_2d)

1D Array: [1 2 3 4 5]
2D Array: [[1 2 3]
 [4 5 6]]


### list vs numpy array 


In [20]:
py_list = [1, 2, 3, 4, 5]
print("python list mulitiplication:", py_list * 2)

np_array = np.array([1, 2, 3]) # element wise multiplication
print("numpy array multiplication:", np_array * 2)

import time 
start  = time.time()
py_list =[i*2 for i in range(1000000)]
print("\n list opration time",time.time() - start)


start = time.time()
np_array = np.arange(1000000) * 2
print("\n numpy opration time",time.time() - start)


python list mulitiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
numpy array multiplication: [2 4 6]

 list opration time 0.05753660202026367

 numpy opration time 0.0038187503814697266


creating array from scratch


In [28]:
zeros = np.zeros((3, 4))
print("Zeros Array:\n", zeros)

ones = np.ones((2, 3)) # this is not a constant value
print("Ones Array:\n", ones)


full = np.full((2, 2), 7) # special constant value in full
print("Full Array:\n", full)


random = np.random.random((2, 2)) # random values
print("Random Array:\n", random)

sequence = np.arange(0, 10, 2) # this value state the start, stop and step
print("Sequence Array:\n", sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[7 7]
 [7 7]]
Random Array:
 [[0.56957544 0.62566588]
 [0.58536121 0.25690152]]
Sequence Array:
 [0 2 4 6 8]


##vector
#vectio,Matrrix and tensor


In [30]:
vector = np.array([1,2,3,4,5])
print("Vector:", vector) 

matrix = np.array([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)  # the add both are 2D matrix


Vector: [1 2 3 4 5]
Matrix:
 [[1 2]
 [3 4]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties

In [32]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape of array:\n", arr.shape)# this are shape are display in row and colome
print("dimension of array:\n", arr.ndim) # this is the dimension of the array
print("size of array:\n", arr.size) # this is the total number of element in the array
print("data type of array:\n", arr.dtype) # this is the data type of the array

shape of array:
 (2, 3)
dimension of array:
 2
size of array:
 6
data type of array:
 int64


Array Reshaping

In [6]:
import numpy as np
arr = np.arange(12) # changing the data type
print("Original array:\n", arr)

reshaped =arr.reshape(3, 4) # reshaping the array
print("Reshaped array:\n", reshaped)


# this is the flattened is copy the replaced value o
flattened = reshaped.flatten()  # flattening the array is mimum one row 
print("Flattened array:\n", flattened)


#revel ( return view , instand of the copy) this is orignal array  
reveled = reshaped.ravel()  
print("Reveled array:\n", reveled)

#transpose (this is the change the row and colome)

transpose = reshaped.T
print("Transposed array:\n", transpose)

Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
