Numpy  Array operations

In [81]:
import numpy as np

In [82]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicimh ", arr[2:7])
print("With Step ", arr[2:6:2]) # gap in list number
print("negative index ", arr[-5:-1])




Basic slicimh  [3 4 5 6 7]
With Step  [3 5]
negative index  [6 7 8 9]


In [83]:
arr_2d = np.array([[1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,15]])
print("enter the specific aray ",arr_2d[1:3]) # this note always number in 0 se start hote hai
print("entire row:",arr_2d[1])
print("entire column:",arr_2d[:,2]) # : means all row and 2 means 3rd column


enter the specific aray  [[ 6  7  8  9 10]
 [11 12 13 14 15]]
entire row: [ 6  7  8  9 10]
entire column: [ 3  8 13]


sorting

In [84]:
unsorted = np.array([3,4,43,6,7,5,5,5,6,6,45,5,4,5,5,6,5,5,])
print("sorted array :",np.sort(unsorted))

arrr_2d_unsorted = np.array([[1,2,3,2,5],
                           [6,7,8,9,1],
                            [11,12,13,14,15]])
print("sorted array:",np.sort(arrr_2d_unsorted)) # axis 0 mea
print("sorted 2d by the row:",np.sort(arrr_2d_unsorted, axis=1))


sorted array : [ 3  4  4  5  5  5  5  5  5  5  5  6  6  6  6  7 43 45]
sorted array: [[ 1  2  2  3  5]
 [ 1  6  7  8  9]
 [11 12 13 14 15]]
sorted 2d by the row: [[ 1  2  2  3  5]
 [ 1  6  7  8  9]
 [11 12 13 14 15]]


## Filter

In [85]:
import numpy as np

numbers =np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers%2==0]
print("even numbers :", even_numbers)

even numbers : [ 2  4  6  8 10]


## filter the mask

In [86]:
mask = numbers >5
print("number greater then 5 ",numbers[mask])

number greater then 5  [ 6  7  8  9 10]


## fancy indexing  np.where*()

In [87]:
indices =[0,2,4]
print(numbers[indices])

where_result =np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])


[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [88]:
condition_array = np.where(numbers >5,"true","false")  
print("condition array", condition_array)

condition array ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [89]:
condition_array = np.where(numbers >3, numbers*4, numbers  )
print("condition array", condition_array)

condition array [ 1  2  3 16 20 24 28 32 36 40]


## adding and removeing data

In [90]:
arr1 =np.array([1,2,3,4,5])
arr2 =np.array([2,3,4,5,6])
combined =np.concatenate((arr1,arr2)) # concatenate is the tow array combine 
print(combined)

[1 2 3 4 5 2 3 4 5 6]


 ## array compatibility

In [91]:
a =np.array([1,2,3])
b  = np.array([1,5,8])
c = np.array([7,8,9])
print("Compatibility shapes", a.shape == b.shape)


Compatibility shapes True


In [98]:
original = np.array([[1,2],[3,4]])
new_row =np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("with new coloum", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new coloum [[1 2 7]
 [3 4 8]]


In [ ]:
arr = np.array([1,3,5,6,7,8])
deleted = np.delete(arr,2)
print("Array after deletation",deleted) # delete opration

Array after deletation [1 3 6 7 8]
